### ISSUE TITLE
角色不受光源影响

### ISSUE THREAD

**Issue by DTEX123** [danbaidong1111/DanbaidongRP#3]
unity 2022.3.7f1 
branch urp14
按readme做完效果是这样的
![20240513195109](https://github.com/danbaidong1111/DanbaidongRP/assets/52734971/dca992c1-5188-4380-b915-ad6445c98ba8)

请问我还缺少那些步骤吗？

**Comment by danbaidong1111** [comment]
可能是InsertedGbuffer Passes那里没设置，你先试试，不行的话周末联系

**Comment by DTEX123** [comment]
好的大佬，我先试试

**Comment by DTEX123** [comment]
加了InsertedGbuffer Passes，只有GBufferOutline有效果
![20240514190555](https://github.com/danbaidong1111/DanbaidongRP/assets/52734971/0f609023-4142-4a0a-9363-02fca69a0dc5)

**Comment by danbaidong1111** [comment]
用release版本啊宝，urp14主开发分支之前在做东西。不过你可以等我urp17的，大概一周后出release。

**Comment by DTEX123** [comment]
OK，我试过release是正常的
期待一下urp17

**Comment by danbaidong1111** [comment]
好哒~
