### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by yuliuren** [danbaidong1111/DanbaidongRP#4]
想问一下现在的版本对于引擎有特定版本要求吗 >6000.0.0和 <6000.0.0都出现不少api报错。

**Comment by danbaidong1111** [comment]
只建议是6000.0.0f1，多一点少一点版本不确定会有没有报错，Unity版本变化SRP的api也不一定变。

**Comment by b4lie** [comment]
> 只建议是6000.0.0f1，多一点少一点版本不确定会有没有报错，Unity版本变化SRP的api也不一定变。

emm 确实 unity6的api变动比较频繁 实测下来 现在最多高2-3个小版本。 期待Unity6正式稳定后大佬的更新😂
